# Generated by Django 3.0.5 on 2020-04-24 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200424_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
